apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "labels.selector" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "labels.selector" . | indent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.configMapController.image.name }}:{{ .Values.configMapController.image.tag }}"
        imagePullPolicy: {{ .Values.configMapController.image.pullPolicy }}
        name: {{ template "name" . }}
      serviceAccountName: {{ template "name" . }}