apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "name" . }}-role
  namespace: {{ .Values.configMapController.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
      - update
      - patch
      - watch
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - deployments
    verbs:
      - list
      - get
      - update
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "name" . }}-role-binding
  namespace: {{ .Values.configMapController.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "name" . }}
    namespace: {{ .Values.configMapController.namespace }}