apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "configmapcontroller.labels.stakater" . | indent 4 }}
{{ include "configmapcontroller.labels.chart" . | indent 4 }}
  name: {{ template "configmapcontroller.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "configmapcontroller.name" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
      - update
      - patch
      - watch
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - deployments
    verbs:
      - list
      - get
      - update
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "configmapcontroller.name" . }}-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "configmapcontroller.name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "configmapcontroller.name" . }}
    namespace: {{ .Release.Namespace }}